#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

print_info () {
    local subdomain="$1"
    local domain="$2"
    local result


    result=$(dig +short "${subdomain}.${domain}")
    
    if [ -z "$result" ]; then
        echo "The subdomain ${subdomain} does not have a valid DNS record."
    else
        echo "The subdomain ${subdomain} is a A record and points to ${result}"
    fi
}
if [ "$#" -eq 2 ]; then
    print_info "$2" "$1"
else
    domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${domains[@]}"; do
        print_info "$subdomain" "$1"
    done
fi
