#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

function print_info {
    local domain="$1"
    local subdomain="$2"
    dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | \
        awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

if [ $# -eq 1 ]; then
    domain="$1"
    sub_domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${sub_domains[@]}"; do
        print_info "$domain" "$subdomain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    print_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
