#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

function print_info {
    dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | \
        awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
    }

if [ $# -eq 1 ];
then
    sub_domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${sub_domains[@]}";
    do
        print_info "$1" "$subdomain"
    done
else
    print_info "$1" "$2"
fi
