#!/usr/bin/env bash
# Update package lists to ensure we have the later

sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
