#!/usr/bin/env bash

# Update package lists to ensure we have the latest information
apt-get -y update
apt-get -y install  nginx

echo "Hello World!" > /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
