#!/usr/bin/env bash

# Update package lists to ensure we have the latest information
apt-get -y update
apt-get -y install  nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i 's/listen 80 default_server/listen 80 default_server;\n\trewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
