#!/usr/bin/env bash
# Installs Nginx with custom configurations

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname; # Use backslash to escape the variable

    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

service nginx restart

echo "Nginx configured with custom settings."
