#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server

sudo apt-get -y update

sudo apt-get install -y haproxy

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 304315-web-01 52.3.241.118:80 check
    server 304315-web-02 54.173.33.44:80 check
EOF

sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
