#!/usr/bin/env bash
# Function to handle SIGTERM and SIGQUIT signals

handle_signals() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 1
}

handle_sigint() {
    echo "Y U no love me?!"
}

trap handle_signals SIGTERM SIGQUIT
trap handle_sigint SIGINT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
