#!/usr/bin/env bash
# 101-manage_my_process script

if [ "${1}" == "start" ]
then
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	pidfile="/var/run/my_process.pid"
	if [ -f "$pidfile" ]; then
	        pid=$(cat "$pidfile")
	        kill "$pid"
	        rm "$pidfile"
	        echo "manage_my_process stopped"
	else
	        echo "manage_my_process is not running"
	fi
elif [ "${1}" == "restart" ]
then
	pidfile="/var/run/my_process.pid"
	if [ -f "$pidfile" ]; then
	        pid=$(cat "$pidfile")
	        kill "$pid"
	        rm "$pidfile"
	else
	        echo "manage_my_process is not running"
	fi
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: $0 {start|stop|restart}"
fi
