#!/usr/bin/env bash
# 101-manage_my_process script

case "$1" in
    "start")
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    
    "stop")
        pidfile="/var/run/my_process.pid"
        if [ -f "$pidfile" ]; then
            pid=$(cat "$pidfile")
            kill "$pid"
            rm "$pidfile"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    
    "restart")
        pidfile="/var/run/my_process.pid"
        if [ -f "$pidfile" ]; then
            pid=$(cat "$pidfile")
            kill "$pid"
            rm "$pidfile"
            ./manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process restarted"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

