#!/usr/bin/env bash
# This script displays "Best School" 10 times, but "Hi" on a new line for the 9th iteration

count=1

while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( count++ ))
done
